version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-net
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}

  backend:
    build: .
    container_name: go-backend
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
      - minio
    networks:
      - backend-net
    environment:
      PORT: ${PORT}
      MONGO_URI: ${MONGO_URI}
      DB_NAME: ${DB_NAME}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_REGION: ${S3_REGION}

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # MinIO Console (UI)
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    command: server /data --console-address ":9001"
    networks:
      - backend-net

volumes:
  mongo-data:
  minio-data:

networks:
  backend-net:
    driver: bridge
